spring:
  application:
    name: Bike

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BikeStoreFinal;encrypt=false;trustServerCertificate=true
    username: sa
    password: Bhuvan@data1208


  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update

server:
  port: 8080
#  servlet:
#    contextpath: /bikestore-services
